language: node_js
node_js:
  - "8"
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  target_branch: master
  github_token: $GITHUB_TOKEN
  repo: nprail/nprail.github.io
  on:
    branch: dev
branches:
  only:
    - dev