name: Node CI

on: 
  push:
    branches:
    - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: npm install, build
      run: |
        npm install
        npm run build
    - name: Deploy GH Pages
      run: |
        rm -rf .git && cd build
        git config --global user.email "bot@nprail.dev"
        git config --global user.name "Deploy Bot"
        git init && git add . && git commit -m "Deploy"
        git remote add origin git@github.com/nprail/nprail.github.io && git push --force
        
